services:
  # Development Backend Service
  komik-crawler-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: komik-crawler-dev
    ports:
      - "3000:3000"
    volumes:
      # Mount source code untuk hot reload
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./nodemon.json:/usr/src/app/nodemon.json
      # Node modules sebagai volume terpisah untuk performa
      - node_modules:/usr/src/app/node_modules
    env_file:
      - .env.dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Untuk file watching di Windows
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/v1/mangas"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dev-network
    
volumes:
  node_modules:

networks:
  dev-network:
    driver: bridge
