services:
  komik-crawler-be:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: komik-crawler-be
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge